# Practical_6: Numpy

Exercise 1:¶
Create a NumPy array of integers from 1 to 10.

## Exercise 1

In [5]:
import numpy as np
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [10]:
x = np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [15]:
x = np.arange(0,5,0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

## Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [18]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [25]:
x = np.random.random((4,4))
x

array([[0.30880238, 0.86431014, 0.41520705, 0.41396696],
       [0.27755985, 0.52677175, 0.31792816, 0.15148174],
       [0.45150509, 0.79043526, 0.88066822, 0.26809996],
       [0.11868423, 0.90778465, 0.39861818, 0.71083243]])

## Exercise 6:
Find the shape of a NumPy array.

In [28]:
x = np.array([1,3,7,4,8])
print(x.shape)

(5,)


## Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [31]:
x = np.arange(1,17).reshape((4,4))
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


## Exercise 8:
Find the data type of the elements in a NumPy array.



In [38]:
x = np.array([1,4,89,45,6.0])
print(x.dtype)

float64


## Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.



In [42]:
x = np.arange(1,100)


## Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.



In [56]:
x = np.random.randint(10,50, size = (6,6))
x

array([[13, 21, 24, 31, 30, 36],
       [46, 19, 43, 17, 32, 24],
       [44, 47, 43, 16, 24, 22],
       [37, 33, 18, 36, 34, 16],
       [46, 24, 21, 24, 18, 39],
       [24, 23, 14, 33, 48, 44]])

## Exercise 11:
Slice a 2D NumPy array to extract a submatrix.



In [75]:
x = np.array(([1,7,0,4,6],[2,4,6,7,9]))
x
y = x[:,3]
y

array([4, 7])

## Exercise 12:
Calculate the sum of all elements in a NumPy array.



In [102]:
x = np.array([[1,6,7],[3,4,10]])
x

array([[ 1,  6,  7],
       [ 3,  4, 10]])

In [104]:
print(np.sum(x)) # SUM OF ALL ELEMENTS

31


In [106]:
t = np.sum(x,0) # SUM BY COLUMN
t

array([ 4, 10, 17])

In [112]:
t = np.sum(x,1) #SUM BY LINE
t

array([14, 17])

## Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.



In [139]:
# mean
x = np.array([[1,6,7],[3,4,10]])
y = np.mean(x,0) # MEAN BY COLUMN
print(y)
z = np.mean(x,1) # MEAN BY LINE
print(z)
moy = np.mean(x)
print(moy)

[2.  5.  8.5]
[4.66666667 5.66666667]
5.166666666666667


In [144]:
# median
x = np.random.randint(100, size = (3,3))
y = np.median(x,0) # MEdian BY COLUMN
print(y)
z = np.median(x,1) # MEdian BY LINE
print(z)
med = np.median(x)
print(med)


[66. 49. 37.]
[49. 84. 21.]
49.0


In [146]:
# standard deviation
x = np.random.randint(100, size = (3,3))
y = np.std(x,0) # standard deviation BY COLUMN
print(y)
z = np.std(x,1) # standard deviation BY LINE
print(z)
stand_dev = np.std(x)
print(stand_dev)

[18.99122604 20.8859336   6.5489609 ]
[21.06075867 17.74510887 11.5758369 ]
17.478734875256453


## Exercise 14:
Find the maximum and minimum values in a NumPy array.



In [152]:
x = np.random.randint(15, size = (2,3))
print(x)
'''
The functions np.argmax or np.argmin return the indices of the maximal valjues or minimum values
'''
# maximum
y = np.argmax(x)
print(y)
y1 = np.argmax(x,0) # by column
print(y1)
y2 = np.argmax(x,1) # by row
print(y2)

# minimum
t = np.argmin(x)
print(t)
t1 = np.argmin(x,0) # by column
print(t1)
t2 = np.argmin(x,1) # by row
print(t2)

[[ 0 13  0]
 [10  1  7]]
1
[1 0 1]
[1 0]
0
[0 1 0]
[0 1]


## Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.



In [156]:
x = np.random.randint(50, size = 20)
y = np.argmax(x)
y

0

## Exercise 16:
Create a NumPy array and reverse its elements.



In [177]:
x = np.random.randint(50, size = 20)
print(x)
y = np.flipud(x)
print(y)

[18 44 10  2 30  0 29 19  0 16 13 26 42 24 46 43 18 12 38 22]
[22 38 12 18 43 46 24 42 26 13 16  0 19 29  0 30  2 10 44 18]


## Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [180]:
x = np.random.randint(50, size = (3,3))
y = np.random.randint(15, size = (3,3))
print(x)
print(y)
t = np.multiply(x,y)
print(t)

[[33 10 11]
 [25 49 47]
 [47 12 12]]
[[ 2  6  4]
 [ 8  4  2]
 [ 6 11 13]]
[[ 66  60  44]
 [200 196  94]
 [282 132 156]]


## Exercise 18:
Create a diagonal matrix from a given 1D array.



In [183]:
x = np.random.randint(10, size = 4)
print(x)
y = np.diag(x)
print(y)


[2 5 9 6]
[[2 0 0 0]
 [0 5 0 0]
 [0 0 9 0]
 [0 0 0 6]]


## Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.



In [188]:
x = np.random.randint(10, size = (2,2))
y = np.random.randint(15, size = (2,2))
t= np.multiply(x,y)
print(t)

[[12 14]
 [20 78]]


## Exercise 20:
Flatten a 2D NumPy array into a 1D array.



In [199]:
x = np.random.randint(10, size = (2,2))
print(x)
y = np.ravel(x)
print(y)

[[7 5]
 [4 9]]
[7 5 4 9]


## Exercise 21:
Stack two NumPy arrays vertically.



In [225]:
x = np.random.randint(10, size = (2,2))
print(x)
y = np.random.randint(15, size = (2,2))
print(y)
t = np.vstack((x,y))
print(t)



[[5 6]
 [0 7]]
[[10 14]
 [ 2  0]]
[[ 5  6]
 [ 0  7]
 [10 14]
 [ 2  0]]


## Exercise 22:
Stack two NumPy arrays horizontally.



In [227]:
x = np.random.randint(10, size = (2,2))
print(x)
y = np.random.randint(15, size = (2,2))
print(y)
t = np.hstack((x,y))
print(t)


[[9 6]
 [5 7]]
[[10 10]
 [ 2  4]]
[[ 9  6 10 10]
 [ 5  7  2  4]]


## Exercise 23:
Split a NumPy array into multiple sub-arrays.



In [235]:
x = np.random.randint(10, size = (4,2))
print(x)
y = np.split(x,2)
print(y)

[[2 4]
 [0 9]
 [9 3]
 [7 6]]
[array([[2, 4],
       [0, 9]]), array([[9, 3],
       [7, 6]])]


## Exercise 24:
Generate a random NumPy array and round each element to two decimal places.



In [246]:
x = np.random.rand(10)
print(x)
y = np.round(x,2)
print(y)

[0.78529823 0.39029736 0.56826507 0.88149883 0.27338928 0.54461898
 0.51233721 0.36131201 0.65273114 0.35912425]
[0.79 0.39 0.57 0.88 0.27 0.54 0.51 0.36 0.65 0.36]


## Exercise 25:
Find the unique elements of a NumPy array.



In [249]:
x = np.random.randint(10, size = 10)
print(x)
y = np.unique(x)
print(y)

[1 7 0 5 8 8 0 2 6 1]
[0 1 2 5 6 7 8]


## Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.



In [254]:
x = np.random.randint(10, size = 10)
x[x <= 4] = 5
print(x)

[6 9 5 5 5 9 9 5 5 7]


## Exercise 27:
Find the cumulative sum of the elements in a NumPy array.



In [257]:
x = np.random.randint(10, size = 10)
print(x)
y = np.cumsum(x)
print(y)


[5 3 4 4 8 5 1 9 0 9]
[ 5  8 12 16 24 29 30 39 39 48]


## Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.



In [262]:
x = np.random.randint(10, size = 10)
print(x)
y = np.count_nonzero(x)
print(y)

[7 7 5 4 5 5 0 4 1 6]
9


## Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.



In [265]:
x = np.random.randint(10, size = 10)
print(x)
y = np.sort(x)
print(y)

[0 0 5 5 6 0 3 9 0 7]
[0 0 0 0 3 5 5 6 7 9]


## Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.



In [268]:
x = np.random.randint(10, size = (3,3))
print(x)
row_wise = np.sum(x, axis = 1)
print(row_wise)
column_wise = np.sum(x, axis = 0)
print(column_wise)

[[0 6 0]
 [4 6 8]
 [5 8 4]]
[ 6 18 17]
[ 9 20 12]


## Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).



In [275]:
x = np.random.randint(10, size = (2,2))
print(x)
x_min = np.min(x)
x_max = np.max(x)
x_norm = (x - x_min) / (x_max - x_min)
print(x_norm)



[[9 0]
 [3 3]]
[[1.         0.        ]
 [0.33333333 0.33333333]]


## Exercise 32:
Create two NumPy arrays and find the dot product.



In [281]:
x = np.random.randint(10, size = 5)
print(x)
y = np.random.randint(15, size = 5)
print(y)
t = np.dot(x,y)
print(t)

[5 7 8 7 7]
[12  2 12  7  1]
226


## Exercise 33:
Find the trace of a square NumPy matrix.



In [284]:
x = np.random.randint(10, size = (3,3))
print(x)
y = np.trace(x)
print(y)

[[4 3 0]
 [6 3 6]
 [3 6 1]]
8


## Exercise 34:
Create a 2D array and swap two rows.



In [289]:
x = np.random.randint(10, size = (2,2))
print(x)
x[0,1] = x[1,0]
print(x)

[[5 3]
 [2 4]]
[[5 2]
 [2 4]]


## Exercise 35:
Create a 1D NumPy array and convert it into a column vector.



In [294]:
x = np.random.randint(10, size = 5)
print(x)
x_column = x[:, np.newaxis]
print(x_column)


[6 7 6 0 1]
[[6]
 [7]
 [6]
 [0]
 [1]]


## Exercise 36:
Find the determinant of a 3x3 matrix.



In [299]:
x = np.random.randint(10, size = (3,3))
print(x)
determinant = np.linalg.det(x)
print(determinant)

[[7 6 0]
 [9 9 2]
 [2 5 1]]
-36.99999999999999


## Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.



In [302]:
x = np.random.randint(10, size = (2,2))
print(x)
eig_va, eig_vec =  np.linalg.eig(x) 
print(eig_va)
print(eig_vec)

[[0 9]
 [9 2]]
[-8.05538514 10.05538514]
[[-0.74512802 -0.66692146]
 [ 0.66692146 -0.74512802]]


## Exercise 38:
Solve a system of linear equations using NumPy.



In [309]:
x = np.random.randint(10, size = (2,2))
y = np.array([4, 5])
sol = np.linalg.solve(x, y)
print(sol)

[ 1.33333333 -0.54166667]


## Exercise 39:
Add Gaussian noise to a NumPy array.



## Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.



In [312]:
x = np.random.randint(10, size = (4,4))
print(x)
diag = np.diagonal(x)
print(diag)


[[0 7 6 0]
 [8 1 5 9]
 [0 8 9 4]
 [7 5 6 7]]
[0 1 9 7]


## Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.



In [316]:
x = np.random.randint(50, size = 100)
print(x)
y = np.clip(x,10,50)
print(y)

[36  9 25 14 48 24 43 10 10 24 27  2 30 32 30  9 13  7  1 30 49 47 40 49
 37 28 34  9 18 13  5 13 39 20 28 19  9 14 20 16  3 39 46 46 21 29 34 28
 16 23 27 37 45 28 41  0 40 31 24 18 43  9 24  0 31 32 43 34 25 25 29 40
 40 23 18 29 30  1  1  0 37 48 49 11 12  5 26 17  6 43 44 18 39 30  1 12
 18 35  1 26]
[36 10 25 14 48 24 43 10 10 24 27 10 30 32 30 10 13 10 10 30 49 47 40 49
 37 28 34 10 18 13 10 13 39 20 28 19 10 14 20 16 10 39 46 46 21 29 34 28
 16 23 27 37 45 28 41 10 40 31 24 18 43 10 24 10 31 32 43 34 25 25 29 40
 40 23 18 29 30 10 10 10 37 48 49 11 12 10 26 17 10 43 44 18 39 30 10 12
 18 35 10 26]


## Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.



In [323]:
x = np.random.randint(-10,10, size = (4,4))
print(x)
x[x < 0] = 0
print(x)

[[  3   0  -7 -10]
 [  3  -5   9   3]
 [  4  -2  -6  -8]
 [ -3  -9  -3   1]]
[[3 0 0 0]
 [3 0 9 3]
 [4 0 0 0]
 [0 0 0 1]]


## Exercise 43:
Find the inner and outer products of two NumPy arrays.



In [326]:
x = np.random.randint(50, size = 10)
y = np.random.randint(25, size = 10)
print(x)
print(y)
inn = np.inner(x, y)
print(inn)
out = np.outer(x, y)
print(out)

[19  0 30  1 33  4 35  7 34 10]
[ 7  8 17  9  4 15  1  3 14 23]
1606
[[133 152 323 171  76 285  19  57 266 437]
 [  0   0   0   0   0   0   0   0   0   0]
 [210 240 510 270 120 450  30  90 420 690]
 [  7   8  17   9   4  15   1   3  14  23]
 [231 264 561 297 132 495  33  99 462 759]
 [ 28  32  68  36  16  60   4  12  56  92]
 [245 280 595 315 140 525  35 105 490 805]
 [ 49  56 119  63  28 105   7  21  98 161]
 [238 272 578 306 136 510  34 102 476 782]
 [ 70  80 170  90  40 150  10  30 140 230]]


## Exercise 44:
Calculate the pairwise distances between points in a NumPy array.



In [329]:
from scipy.spatial.distance import pdist, squareform
x = np.random.randint(-10,10, size = (4,4))
print(x)
distances = squareform(pdist(x, metric='euclidean'))
print(distances)


[[  5  -5   1  -3]
 [  2  -3   9  -5]
 [-10   9   7   1]
 [  9  -1  -9   4]]
[[ 0.          9.         21.74856317 13.45362405]
 [ 9.          0.         18.11077028 21.40093456]
 [21.74856317 18.11077028  0.         26.94438717]
 [13.45362405 21.40093456 26.94438717  0.        ]]


## Exercise 45:
Create a structured NumPy array with fields for name, age, and height.



In [332]:
Liste = [('Carine', 25, 5.5),('Frieda', 30, 6.0),('Paul', 35, 5.8)]
x = np.array(Liste, dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])
print(x)



[('Carine', 25, 5.5) ('Frieda', 30, 6. ) ('Paul', 35, 5.8)]


## Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.



In [335]:
from collections import Counter
x = np.random.randint(10, size = (5,5))
print(x)
# convert in 1D
x_1 = x.flatten()
occurrences = Counter(x_1)
print(occurrences)


[[1 4 3 1 6]
 [4 4 0 1 8]
 [9 8 9 6 4]
 [3 0 9 4 0]
 [2 1 2 3 3]]
Counter({4: 5, 1: 4, 3: 4, 0: 3, 9: 3, 6: 2, 8: 2, 2: 2})


## Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.



In [338]:
x = np.random.randint(10, size=(3, 3))
print(x)
row_mean = np.mean(x, axis=1)
print(row_mean)
x_mean = x - row_mean
print(x_mean)


[[0 5 8]
 [7 9 6]
 [1 9 9]]
[4.33333333 7.33333333 6.33333333]
[[-4.33333333 -2.33333333  1.66666667]
 [ 2.66666667  1.66666667 -0.33333333]
 [-3.33333333  1.66666667  2.66666667]]


## Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.



In [341]:
x = np.random.randint(1, 100, size=10)
print(x)
numbers = np.any(x > 50)
print(numbers)


[67 74 74 80 27 14 54 68 93 28]
True


## Exercise 49:
Calculate the moving average of a 1D NumPy array.



## Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.



In [345]:
x = np.random.randint(1, 100, size=10)
y = np.random.randint(1, 50, size=10)
corr = np.corrcoef(x, y)
pear_cor = corr[0, 1]
print(pear_cor)


-0.5493883490431044


## Exercise 51:
Convert a NumPy array of radians to degrees.



## Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.



In [349]:
x = np.random.randint(1, 100, size=5)
var = np.var(x)
print(var)
stan_dev = np.std(x)
print(stan_dev)

930.1600000000001
30.498524554476404


## Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


## Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.



In [355]:
x = np.random.randint(10, size=(3, 3))
print(x)
inv_mat = np.linalg.inv(x)
print(inv_mat)


[[8 6 2]
 [8 6 9]
 [9 5 8]]
[[ 0.03061224 -0.3877551   0.42857143]
 [ 0.17346939  0.46938776 -0.57142857]
 [-0.14285714  0.14285714 -0.        ]]


Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

# Exercise 55

Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

# Exercise 56

Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

# Exercise 57

Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

# Exercise 58

Exercise 59:
Compute the Frobenius norm of a matrix.

# Exercise 59

=Exercise 60:
Create a 3D NumPy array and slice out a subarray.

# Exercise 60